import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#393057",
        "surface-tint": "#575f72",
        "on-secondary-container": "#435368",
        "tertiary": "#635983",
        "background": "#f9f9f8",
        "surface-container-low": "#f3f4f3",
        "error-dim": "#67040d",
        "tertiary-dim": "#574d76",
        "primary-fixed-dim": "#cdd4ea",
        "surface-container": "#eceeed",
        "on-tertiary-fixed-variant": "#564c76",
        "surface-container-highest": "#e0e3e2",
        "on-primary-fixed": "#373f51",
        "surface-bright": "#f9f9f8",
        "on-primary-fixed-variant": "#545b6e",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#dbe2f9",
        "surface-container-high": "#e6e9e8",
        "on-primary-container": "#4a5264",
        "on-surface-variant": "#5b605f",
        "on-secondary-fixed": "#314055",
        "surface-variant": "#e0e3e2",
        "on-background": "#2f3333",
        "on-surface": "#2f3333",
        "secondary-fixed": "#d3e4fe",
        "secondary-fixed-dim": "#c5d6f0",
        "tertiary-container": "#dbcdff",
        "secondary-container": "#d3e4fe",
        "secondary": "#506076",
        "inverse-surface": "#0c0f0e",
        "on-tertiary-container": "#4d436c",
        "outline": "#777c7b",
        "on-error-container": "#6e0a12",
        "tertiary-fixed-dim": "#ccc0f0",
        "on-tertiary": "#fdf7ff",
        "inverse-primary": "#e0e8ff",
        "primary-fixed": "#dbe2f9",
        "inverse-on-surface": "#9c9d9c",
        "on-secondary": "#f7f9ff",
        "secondary-dim": "#44546a",
        "on-error": "#fff7f6",
        "on-secondary-fixed-variant": "#4d5d73",
        "error-container": "#fa746f",
        "surface": "#f9f9f8",
        "primary": "#575f72",
        "error": "#a83836",
        "on-primary": "#f9f8ff",
        "primary-dim": "#4b5366",
        "surface-dim": "#d7dbda",
        "outline-variant": "#afb3b2",
        "tertiary-fixed": "#dbcdff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
